---
- name: Install required dependencies for Caddy repository
  ansible.builtin.apt:
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - curl
    state: present
  become: true

- name: Add Caddy GPG key
  ansible.builtin.shell: >
    set -o pipefail;
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' |
    gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  become: true
  changed_when: false

- name: Add Caddy apt repository
  ansible.builtin.shell: >
    set -o pipefail;
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' |
    tee /etc/apt/sources.list.d/caddy-stable.list
  args:
    creates: /etc/apt/sources.list.d/caddy-stable.list
  become: true
  changed_when: false

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install Caddy
  ansible.builtin.apt:
    name: caddy
    state: present
  become: true
