---
- name: Check if plugin is already installed
  ansible.builtin.shell: |
    set -o pipefail
    export PATH="{{ asdf_binary_install_path }}:${PATH}"
    export ASDF_DATA_DIR="{{ asdf_dir }}"
    asdf plugin list | grep -w "{{ plugin.name }}"
  args:
    executable: /bin/zsh
  register: asdf_plugin_check
  changed_when: false
  failed_when: false

- name: Add asdf plugin
  ansible.builtin.shell: |
    set -o pipefail
    export PATH="{{ asdf_binary_install_path }}:${PATH}"
    export ASDF_DATA_DIR="{{ asdf_dir }}"
    asdf plugin add "{{ plugin.name }}" "{{ plugin.url }}"
  args:
    executable: /bin/zsh
  when: asdf_plugin_check.rc != 0
  changed_when: true
  retries: 3
  delay: 5

- name: Install plugin versions
  ansible.builtin.shell: |
    set -o pipefail
    export PATH="{{ asdf_binary_install_path }}:${PATH}"
    export ASDF_DATA_DIR="{{ asdf_dir }}"
    asdf install "{{ plugin.name }}" "{{ item }}"
  args:
    executable: /bin/zsh
  loop: "{{ plugin.versions }}"
  register: asdf_install_result
  changed_when: "'already installed' not in asdf_install_result.stderr"
  failed_when: false
  retries: 3
  delay: 5

- name: Set global version
  ansible.builtin.shell: |
    set -o pipefail
    export PATH="{{ asdf_binary_install_path }}:${PATH}"
    export ASDF_DATA_DIR="{{ asdf_dir }}"
    asdf set -u "{{ plugin.name }}" "{{ plugin.global }}"
  args:
    executable: /bin/zsh
  when: plugin.global is defined
  changed_when: true

- name: Verify plugin installation
  ansible.builtin.shell: |
    set -o pipefail
    export PATH="{{ asdf_binary_install_path }}:${PATH}"
    export ASDF_DATA_DIR="{{ asdf_dir }}"
    asdf current "{{ plugin.name }}"
  args:
    executable: /bin/zsh
  register: asdf_plugin_version_output
  changed_when: false
