---
- name: Check if asdf is installed
  ansible.builtin.stat:
    path: "{{ dotfiles_home }}/.local/bin/asdf"
  register: asdf_check
  failed_when: not asdf_check.stat.exists

- name: Manage zoxide via asdf
  ansible.builtin.include_role:
    name: asdf
    tasks_from: plugin.yml
  vars:
    plugin:  # noqa: var-naming[no-role-prefix]
      name: zoxide
      url: "{{ zoxide_plugin_url }}"
      versions:
        - "{{ zoxide_version }}"
      global: "{{ zoxide_version }}"
