---
- name: Get current shell
  ansible.builtin.shell: echo $SHELL
  register: zsh_current_shell
  changed_when: false

- name: Clone zinit repository
  ansible.builtin.git:
    repo: "{{ zsh_zinit_repo }}"
    dest: "{{ zsh_zinit_home }}"
    version: main
    force: true
    single_branch: true
  when: zsh_zinit_enabled

- name: Generate zsh configuration
  ansible.builtin.template:
    src: zshrc.j2
    dest: "{{ dotfiles_home }}/.zshrc"
    mode: '0644'
    backup: true
  when: zsh_config_enabled

- name: Install powerlevel10k configuration
  ansible.builtin.copy:
    src: p10k.zsh
    dest: "{{ dotfiles_home }}/.p10k.zsh"
    mode: '0644'
  when:
    - zsh_p10k_enabled
    - zsh_p10k_config_enabled

- name: Create zsh cache directory
  ansible.builtin.file:
    path: "{{ dotfiles_home }}/.cache/zsh"
    state: directory
    mode: '0755'
