---
- name: Apply Git configuration template
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "{{ dotfiles_home }}/.gitconfig"
    mode: '0644'
    backup: true

- name: Create lazygit config directory
  ansible.builtin.file:
    path: >-
      {{
        dotfiles_home + '/Library/Application Support/lazygit'
        if ansible_os_family == 'Darwin'
        else dotfiles_home + '/.config/lazygit'
      }}
    state: directory
    mode: '0755'

- name: Apply lazygit configuration template
  ansible.builtin.template:
    src: lazygit_config.yml.j2
    dest: >-
      {{
        (dotfiles_home + '/Library/Application Support/lazygit')
        if ansible_os_family == 'Darwin'
        else (dotfiles_home + '/.config/lazygit')
      }}/config.yml
    mode: '0644'
    backup: true
