---
- name: Check if Homebrew is already installed
  ansible.builtin.stat:
    path: "{{ homebrew_bin_path }}/brew"
  register: homebrew_installed

- name: Install Homebrew package manager
  ansible.builtin.shell: |
    /bin/bash -c "$(curl -fsSL {{ homebrew_install_url }})"
  when: not homebrew_installed.stat.exists
  changed_when: true
  retries: "{{ homebrew_install_retries }}"
  delay: "{{ homebrew_install_delay }}"
  timeout: "{{ homebrew_install_timeout }}"
  environment:
    NONINTERACTIVE: "1"
  no_log: true

- name: Add Homebrew to PATH in shell profile
  ansible.builtin.lineinfile:
    path: "{{ dotfiles_home }}/.zprofile"
    line: "{{ homebrew_shell_env_command }}"
    create: true
    mode: '0644'
  when: not homebrew_installed.stat.exists

- name: Verify Homebrew installation
  ansible.builtin.command: "{{ homebrew_bin_path }}/brew --version"
  register: homebrew_version
  changed_when: false
  retries: 3
  delay: 2
