---
fonts_jetbrains_mono_nerd_enabled: true
fonts_jetbrains_mono_nerd_homebrew_cask: "font-jetbrains-mono-nerd-font"
fonts_jetbrains_mono_nerd_download_url: >-
  https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/JetBrainsMono.zip

fonts_refresh_cache: true
